# Generated by Django 5.2.6 on 2025-09-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A friendly name for this connection', max_length=100)),
                ('connection_type', models.CharField(choices=[('SSH', 'SSH'), ('CENTRALIZED', 'Centralized Pipeline Management')], help_text='Type of connection (SSH or Centralized)', max_length=20)),
                ('host', models.CharField(blank=True, help_text='Hostname or IP address for SSH connection', max_length=255, null=True)),
                ('port', models.PositiveIntegerField(blank=True, default=22, help_text='SSH port (default: 22)', null=True)),
                ('username', models.CharField(blank=True, help_text='Username for authentication', max_length=100, null=True)),
                ('password', models.CharField(blank=True, help_text='Password for authentication (leave empty if using SSH key)', max_length=255, null=True)),
                ('ssh_key', models.TextField(blank=True, help_text='SSH private key (PEM format) for key-based authentication', null=True)),
                ('cloud_id', models.CharField(blank=True, help_text='Elastic Cloud ID for centralized management', max_length=255, null=True)),
                ('cloud_url', models.URLField(blank=True, help_text='Elastic Cloud URL (alternative to Cloud ID)', null=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication (alternative to username/password)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connections',
                'ordering': ['name'],
            },
        ),
    ]
