# Generated by Django 6.0 on 2026-02-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for authentication (alternative to username/password)', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=models.CharField(blank=True, help_text='Password for authentication (leave empty if using SSH key)', max_length=512, null=True),
        ),
    ]
