# Generated by Django 6.0 on 2026-02-28 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PipelineManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this credential', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this credential')),
                ('version', models.CharField(choices=[('1', 'SNMPv1'), ('2c', 'SNMPv2c'), ('3', 'SNMPv3')], default='2c', help_text='SNMP version (1, 2c, or 3)', max_length=2)),
                ('community', models.CharField(blank=True, default='public', help_text='Community string for SNMPv1/v2c (default: public)', max_length=255)),
                ('security_name', models.CharField(blank=True, help_text='SNMPv3 security name or user name', max_length=255)),
                ('security_level', models.CharField(blank=True, choices=[('noAuthNoPriv', 'No Authentication, No Privacy'), ('authNoPriv', 'Authentication, No Privacy'), ('authPriv', 'Authentication and Privacy')], help_text='SNMPv3 security level', max_length=20)),
                ('auth_protocol', models.CharField(blank=True, choices=[('md5', 'MD5'), ('sha', 'SHA'), ('sha2', 'SHA2'), ('hmac128sha224', 'HMAC128-SHA224'), ('hmac192sha256', 'HMAC192-SHA256'), ('hmac256sha384', 'HMAC256-SHA384'), ('hmac384sha512', 'HMAC384-SHA512')], help_text='SNMPv3 authentication protocol', max_length=20)),
                ('auth_pass', models.CharField(blank=True, help_text='SNMPv3 authentication passphrase or password', max_length=255)),
                ('priv_protocol', models.CharField(blank=True, choices=[('des', 'DES'), ('3des', '3DES'), ('aes', 'AES'), ('aes128', 'AES128'), ('aes192', 'AES192'), ('aes256', 'AES256'), ('aes256with3desKey', 'AES256 with 3DES Key')], help_text='SNMPv3 privacy/encryption.py protocol', max_length=20)),
                ('priv_pass', models.CharField(blank=True, help_text='SNMPv3 encryption.py password', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SNMP Credential',
                'verbose_name_plural': 'SNMP Credentials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name for this profile (e.g., 'cisco_custom', 'my_switch_profile')", max_length=255, unique=True)),
                ('profile_data', models.JSONField(help_text='JSON blob containing the profile configuration (OIDs, metrics, etc.)')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this profile is for')),
                ('type', models.CharField(blank=True, help_text='Type/category of devices this profile is for (e.g., Network, Server, Any)', max_length=100)),
                ('vendor', models.CharField(blank=True, help_text='Vendor or manufacturer this profile is designed for (e.g., Cisco, Generic, Any)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SNMP Profile',
                'verbose_name_plural': 'SNMP Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this network', max_length=255, unique=True)),
                ('network_range', models.CharField(help_text='Network in CIDR notation (e.g., 192.168.1.0/24)', max_length=50)),
                ('logstash_name', models.CharField(blank=True, help_text='Name of the Logstash node that will monitor this network (deprecated, use connection instead)', max_length=255)),
                ('discovery_enabled', models.BooleanField(default=True, help_text='Enable automatic device discovery on this network')),
                ('traps_enabled', models.BooleanField(default=False, help_text='Enable SNMP traps for this network')),
                ('interval', models.PositiveIntegerField(default=30, help_text='Polling interval in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, help_text='Logstash connection that will monitor this network', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snmp_networks', to='PipelineManager.connection')),
                ('credential', models.ForeignKey(blank=True, help_text='SNMP credential to use for trap reception on this network', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trap_networks', to='SNMP.credential')),
                ('discovery_credential', models.ForeignKey(blank=True, help_text='SNMP credential to use for device discovery on this network', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_networks', to='SNMP.credential')),
            ],
            options={
                'verbose_name': 'SNMP Network',
                'verbose_name_plural': 'SNMP Networks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this device', max_length=255, unique=True)),
                ('ip_address', models.CharField(help_text='IP address or hostname of the device', max_length=255)),
                ('port', models.IntegerField(default=161, help_text='SNMP port (default: 161)')),
                ('retries', models.IntegerField(default=2, help_text='Number of retries for SNMP requests (default: 2)')),
                ('timeout', models.IntegerField(default=1000, help_text='Timeout in milliseconds for SNMP requests (default: 1000)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(blank=True, help_text='SNMP credential to use for this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='SNMP.credential')),
                ('network', models.ForeignKey(blank=True, help_text='Network this device belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='SNMP.network')),
                ('profiles', models.ManyToManyField(blank=True, help_text='SNMP profiles to apply to this device', related_name='devices', to='SNMP.profile')),
            ],
            options={
                'verbose_name': 'SNMP Device',
                'verbose_name_plural': 'SNMP Devices',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='SNMP_device_name_087021_idx'), models.Index(fields=['ip_address'], name='SNMP_device_ip_addr_6a90e5_idx'), models.Index(fields=['-created_at'], name='SNMP_device_created_becb56_idx'), models.Index(fields=['network', 'name'], name='SNMP_device_network_889f1c_idx')],
            },
        ),
    ]
