# Generated by Django 6.0.3 on 2026-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this device template', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this template is for')),
                ('vendor', models.CharField(blank=True, help_text='Vendor or manufacturer this template is designed for (e.g., Cisco, Juniper, Generic)', max_length=100)),
                ('type', models.CharField(blank=True, help_text='Type/category of devices this template is for (e.g., Router, Switch, Firewall)', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Specific model identifier (e.g., Catalyst 9300, ASR 1000)', max_length=100)),
                ('matching_rules', models.JSONField(blank=True, default=list, help_text='List of substrings to match against device sysDescr or other identifying fields for auto-assignment')),
                ('official', models.BooleanField(default=False, help_text='Whether this is an official/built-in template (official templates cannot be edited or deleted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profiles', models.ManyToManyField(blank=True, help_text='SNMP profiles to apply when this template is assigned to a device', related_name='device_templates', to='SNMP.profile')),
            ],
            options={
                'verbose_name': 'Device Template',
                'verbose_name_plural': 'Device Templates',
                'ordering': ['name'],
            },
        ),
    ]
