# Generated by Django 6.0.3 on 2026-04-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0002_devicetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetemplate',
            name='type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
        migrations.AlterField(
            model_name='devicetemplate',
            name='vendor',
            field=models.CharField(help_text='Vendor or manufacturer this template is designed for (e.g., Cisco, Juniper, Generic)', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vendor',
            field=models.CharField(help_text='Vendor or manufacturer this profile is designed for (e.g., Cisco, Generic, Any)', max_length=100),
        ),
    ]
