# Generated by Django 6.0.3 on 2026-04-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0003_remove_devicetemplate_type_remove_profile_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_template',
            field=models.ForeignKey(blank=True, help_text='Device template assigned to this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='SNMP.devicetemplate'),
        ),
    ]
