# Generated by Django 6.0.3 on 2026-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0004_device_device_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetemplate',
            name='product',
            field=models.CharField(blank=True, help_text='Product or device type this template is designed for (e.g., Switch, Router, Server, iDRAC)', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.CharField(blank=True, help_text='Product or device type this profile is designed for (e.g., Switch, Router, Server, iDRAC)', max_length=100),
        ),
    ]
