# Generated by Django 6.0.3 on 2026-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0005_devicetemplate_product_profile_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetemplate',
            name='model',
            field=models.CharField(blank=True, help_text='Specific model number (e.g., 9300, 1000)', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicetemplate',
            name='product',
            field=models.CharField(blank=True, help_text='Product line or series (e.g., iDRAC, Catalyst, ASR)', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='product',
            field=models.CharField(blank=True, help_text='Product line or series (e.g., iDRAC, Catalyst, ASR)', max_length=100),
        ),
    ]
