# Generated by Django 6.0.3 on 2026-04-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0006_alter_devicetemplate_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='profiles',
        ),
    ]
