# Generated by Django 6.0.3 on 2026-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0007_remove_device_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetemplate',
            name='type',
            field=models.CharField(blank=True, help_text='Device type (e.g., Router, Switch, Server, Firewall)', max_length=100),
        ),
    ]
