# Generated by Django 6.0.3 on 2026-06-08 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0009_alter_device_device_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_template',
            field=models.ForeignKey(blank=True, help_text="Device template assigned to this device (defaults to 'Default' template if not specified)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='SNMP.devicetemplate'),
        ),
    ]
