# Generated by Django 6.0.3 on 2026-06-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0010_alter_device_device_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='namespace',
            field=models.CharField(default='default', help_text='Data stream namespace for organizing data (e.g., dev, prod, qa). Max 100 bytes.', max_length=100),
        ),
    ]
