# Generated by Django 6.0.3 on 2026-06-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0011_network_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='normalizers',
            field=models.JSONField(blank=True, default=list, help_text='List of normalizer configurations to apply to profile fields'),
        ),
    ]
