# Generated by Django 6.0.3 on 2026-06-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0012_profile_normalizers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPDeploymentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_deployment', models.DateTimeField(blank=True, help_text='Timestamp of last successful deployment', null=True)),
                ('last_config_change', models.DateTimeField(auto_now=True, help_text='Timestamp of last configuration change')),
            ],
            options={
                'verbose_name': 'SNMP Deployment State',
                'verbose_name_plural': 'SNMP Deployment State',
                'db_table': 'snmp_deployment_state',
            },
        ),
    ]
