# Generated by Django 6.0.3 on 2026-06-10 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0014_alter_snmpdeploymentstate_last_config_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snmpdeploymentstate',
            name='last_config_change',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 6, 10, 19, 42, 38, 772260, tzinfo=datetime.timezone.utc), help_text='Timestamp of last configuration change'),
            preserve_default=False,
        ),
    ]
