# Generated by Django 6.0.3 on 2026-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0015_alter_snmpdeploymentstate_last_config_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snmpdeploymentstate',
            name='last_config_change',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last configuration change', null=True),
        ),
    ]
