# Generated by Django 6.0.3 on 2026-06-11 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0016_alter_snmpdeploymentstate_last_config_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='logstash_name',
        ),
    ]
