# Generated by Django 6.0.3 on 2026-06-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0018_add_official_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='namespace_from_device_template',
            field=models.BooleanField(default=False, help_text='When enabled, the normalized device template name is used as the data stream namespace instead of the fixed namespace value.'),
        ),
    ]
