# Generated by Django 6.0.3 on 2026-06-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0019_network_namespace_from_device_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, help_text='DNS hostname of the device (optional if IP address is provided)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(blank=True, help_text='IP address of the device (optional if hostname is provided)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['hostname'], name='SNMP_device_hostnam_fae88a_idx'),
        ),
    ]
