# Generated by Django 6.0.3 on 2026-06-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0020_device_hostname_alter_device_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='building',
            field=models.CharField(blank=True, help_text='Building within the site', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geographic latitude of the device location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geographic longitude of the device location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value metadata for this device'),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.CharField(blank=True, help_text='Room or rack location within the building', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.CharField(blank=True, help_text='Site or campus this device is located at', max_length=255, null=True),
        ),
    ]
