# Generated by Django 6.0.3 on 2026-06-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0021_device_building_device_latitude_device_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Geographic latitude of the device location', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Geographic longitude of the device location', max_digits=15, null=True),
        ),
    ]
