# Generated by Django 6.0.3 on 2026-06-29 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0021_connection_desired_agent_version'),
        ('SNMP', '0022_alter_device_latitude_alter_device_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='agent_connection',
            field=models.ForeignKey(blank=True, help_text='LogstashAgent connection for deployment (AGENT mode only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_snmp_networks', to='PipelineManager.connection'),
        ),
        migrations.AddField(
            model_name='network',
            name='deployment_mode',
            field=models.CharField(choices=[('CENTRALIZED', 'Centralized Pipeline Management'), ('AGENT', 'LogstashAgent')], default='CENTRALIZED', help_text='Deployment mode for this network (Centralized Pipeline Management or LogstashAgent)', max_length=20),
        ),
        migrations.AlterField(
            model_name='network',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Elasticsearch connection for this network', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snmp_networks', to='PipelineManager.connection'),
        ),
    ]
