# Generated by Django 6.0.3 on 2026-06-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0023_network_agent_connection_network_deployment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='credential_mode',
            field=models.CharField(choices=[('KEYSTORE', 'Manage Keystore Manually'), ('PLAINTEXT', 'Plaintext Credentials')], default='KEYSTORE', help_text='How credentials are supplied to pipelines (Centralized Pipeline Management mode only)', max_length=20),
        ),
    ]
