# Generated by Django 6.0 on 2026-03-21 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0002_alter_connection_connection_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Policy name', max_length=100, unique=True)),
                ('settings_path', models.CharField(default='/etc/logstash/', help_text='Path to Logstash settings directory', max_length=255)),
                ('logs_path', models.CharField(default='/var/log/logstash', help_text='Path to Logstash logs directory', max_length=255)),
                ('logstash_yml', models.TextField(help_text='Content of logstash.yml configuration file')),
                ('jvm_options', models.TextField(help_text='Content of jvm.options configuration file')),
                ('log4j2_properties', models.TextField(help_text='Content of log4j2.properties configuration file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='connection',
            name='policy',
            field=models.ForeignKey(blank=True, help_text='Policy to apply to this agent (only for AGENT connection type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='PipelineManager.policy'),
        ),
    ]
