# Generated by Django 6.0 on 2026-03-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0007_alter_enrollmenttoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='agent_id',
            field=models.CharField(blank=True, help_text='Unique agent ID for Agent connections', max_length=255, null=True, unique=True),
        ),
    ]
