# Generated by Django 6.0 on 2026-03-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0008_connection_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='last_check_in',
            field=models.DateTimeField(blank=True, help_text='Last time the agent checked in with LogstashUI', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='jvm_options_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA256 hash of jvm.options content', max_length=64),
        ),
        migrations.AddField(
            model_name='policy',
            name='log4j2_properties_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA256 hash of log4j2.properties content', max_length=64),
        ),
        migrations.AddField(
            model_name='policy',
            name='logstash_yml_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA256 hash of logstash.yml content', max_length=64),
        ),
    ]
