# Generated by Django 6.0 on 2026-03-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0010_keystore_revision_number_pipeline_revision_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystore',
            name='kv_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA256 hash of key_name + key_value for change detection', max_length=64),
        ),
    ]
