# Generated by Django 5.2.11 on 2026-03-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this credential', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this credential')),
                ('protocol', models.CharField(choices=[('restconf', 'RESTCONF'), ('netconf', 'NETCONF'), ('rest', 'Vendor REST API')], default='restconf', help_text='Protocol this credential is used with', max_length=20)),
                ('auth_type', models.CharField(choices=[('basic', 'HTTP Basic Auth'), ('token', 'Bearer Token'), ('api_key', 'API Key'), ('certificate', 'Client Certificate')], default='basic', help_text='Authentication type', max_length=20)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=512)),
                ('token', models.CharField(blank=True, max_length=2048)),
                ('api_key_header', models.CharField(blank=True, default='X-API-Key', max_length=100)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network Credential',
                'verbose_name_plural': 'Network Credentials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this profile', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('vendor', models.CharField(blank=True, help_text='Vendor this profile targets (e.g. Cisco, Juniper, Generic)', max_length=100)),
                ('type', models.CharField(blank=True, help_text='Category: Router, Switch, Firewall, etc.', max_length=100)),
                ('profile_data', models.JSONField(help_text='JSON object describing data collection paths (YANG, REST, NETCONF filter)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network Config Profile',
                'verbose_name_plural': 'Network Config Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this device', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(choices=[('cisco_ios', 'Cisco IOS/IOS-XE'), ('cisco_nxos', 'Cisco NX-OS'), ('cisco_iosxr', 'Cisco IOS-XR'), ('juniper', 'Juniper Junos'), ('arista', 'Arista EOS'), ('paloalto', 'Palo Alto'), ('fortinet', 'Fortinet FortiOS'), ('generic', 'Generic')], default='generic', max_length=50)),
                ('hostname', models.CharField(help_text='IP address or hostname of the device', max_length=255)),
                ('rest_port', models.PositiveIntegerField(default=443, help_text='Port for REST/RESTCONF (default: 443)')),
                ('netconf_port', models.PositiveIntegerField(default=830, help_text='Port for NETCONF SSH (default: 830)')),
                ('use_restconf', models.BooleanField(default=True)),
                ('use_netconf', models.BooleanField(default=False)),
                ('last_status', models.CharField(choices=[('unknown', 'Unknown'), ('reachable', 'Reachable'), ('unreachable', 'Unreachable'), ('error', 'Error')], default='unknown', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_status_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(blank=True, help_text='Credential to use for this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='NetworkConfig.credential')),
                ('profile', models.ForeignKey(blank=True, help_text='Configuration profile to apply to this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='NetworkConfig.profile')),
            ],
            options={
                'verbose_name': 'Network Device',
                'verbose_name_plural': 'Network Devices',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='NetworkConf_name_c4dbf7_idx'), models.Index(fields=['hostname'], name='NetworkConf_hostnam_d4e1ba_idx'), models.Index(fields=['-created_at'], name='NetworkConf_created_51f5f9_idx'), models.Index(fields=['last_status'], name='NetworkConf_last_st_89cc03_idx')],
            },
        ),
    ]
