input { pipeline { address => "output-block" } }

filter { }

output {
  http {
    id => "http-output-to-logstashui"
    http_method => "post"
    url => "http://host.docker.internal:8080/API/StreamSimulate/"
    format => "json"
    content_type => "application/json"
  }
}
