input { pipeline { address => "simulate-end" } }

filter {
  # Mark this as the final step
  ruby {
    id => "sim_end_ruby"
    code => "event.set('[simulation_step]', event.get('[simulation_step]').to_i + 1); event.set('[step_id]', 'final')"
  }
}

output {
  # Send final message to StreamSimulate
  http {
    id => "sim_start_http"
    http_method => "post"
    url => "http://host.docker.internal:8080/API/StreamSimulate/"
    format => "json"
    content_type => "application/json"
  }
}
