input { pipeline { address => "filter-final" } }

filter {
  ruby {
    code => "
      snapshot = event.to_hash.clone
      snapshot.delete('pipeline_snapshot')
      event.set('[pipeline_snapshot][final]', snapshot)
    "
  }
}

output {
  pipeline { send_to => "output-block" }
}
