input {
  http {
    port => 8082
    codec => json
  }
}

filter {
  mutate {
    id => "a000-input-prune-added-fields"
    rename => {"url" => "[@metadata][pruned][url]"}
    rename => {"http" => "[@metadata][pruned][http]"}
    rename => {"user_agent" => "[@metadata][pruned][user_agent]"}
    remove_field => ["[host][ip]"]
    add_field => {"[host][name]" => "LOGSTASH-HOST"}
  }
}

output {
  pipeline { send_to => "filter1" }
}
