# Generated by Django 6.0.3 on 2026-07-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_draftdefinition_normalizers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AISettings',
        ),
        migrations.DeleteModel(
            name='DraftDefinition',
        ),
    ]
