# Generated by Django 6.0 on 2026-02-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(choices=[('AGENT', 'Logstash Agent'), ('CENTRALIZED', 'Centralized Pipeline Management')], help_text='Type of connection (Agent or Centralized)', max_length=20),
        ),
        migrations.AlterField(
            model_name='connection',
            name='host',
            field=models.CharField(blank=True, help_text='Hostname or IP address for Agent connection', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=models.CharField(blank=True, help_text='Password for authentication (leave empty if using key-based auth)', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=22, help_text='Agent port (default: 22)', null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='ssh_key',
            field=models.TextField(blank=True, help_text='Private key (PEM format) for key-based authentication', null=True),
        ),
    ]
