# Generated by Django 6.0 on 2026-03-22 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0003_policy_connection_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='current_revision_number',
            field=models.IntegerField(default=0, help_text='Current revision number of the policy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='has_undeployed_changes',
            field=models.BooleanField(default=True, help_text="Indicates if there are changes that haven't been deployed"),
        ),
        migrations.CreateModel(
            name='Keystore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(help_text='Key name (unique within policy)', max_length=100)),
                ('key_value', models.CharField(help_text='Encrypted key value', max_length=512)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(help_text='Policy this keystore entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='keystore_entries', to='PipelineManager.policy')),
            ],
            options={
                'verbose_name': 'Keystore Entry',
                'verbose_name_plural': 'Keystore Entries',
                'ordering': ['policy', 'key_name'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'key_name'), name='unique_key_per_policy')],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pipeline name (unique within policy)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the pipeline', null=True)),
                ('lscl', models.TextField(help_text='Logstash Configuration Language (pipeline configuration)')),
                ('lscl_hash', models.CharField(blank=True, help_text='Hash of the LSCL content for change detection', max_length=64, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(help_text='Policy this pipeline belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='PipelineManager.policy')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['policy', 'name'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'name'), name='unique_pipeline_per_policy')],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(help_text='Revision number for this deployment')),
                ('snapshot_json', models.JSONField(help_text='Complete serialized state including config files, pipelines, and keystore entries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(help_text='Username of the user who created this revision', max_length=150)),
                ('policy', models.ForeignKey(help_text='Policy this revision belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='PipelineManager.policy')),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
                'ordering': ['-revision_number', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'revision_number'), name='unique_revision_per_policy')],
            },
        ),
    ]
