# Generated by Django 6.0 on 2026-03-22 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0004_policy_current_revision_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Hashed API key for agent authentication', max_length=512)),
                ('connection', models.ForeignKey(help_text='Connection this API key belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='PipelineManager.connection')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Enrollment token string', max_length=512)),
                ('policy', models.ForeignKey(help_text='Policy this enrollment token is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='PipelineManager.policy')),
            ],
            options={
                'verbose_name': 'Enrollment Token',
                'verbose_name_plural': 'Enrollment Tokens',
            },
        ),
    ]
