# Generated by Django 6.0 on 2026-03-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0005_apikey_enrollmenttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmenttoken',
            name='name',
            field=models.CharField(default='default', help_text='Name for this enrollment token', max_length=100),
        ),
    ]
