# Generated by Django 6.0 on 2026-03-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0006_enrollmenttoken_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmenttoken',
            options={'ordering': ['policy', 'name'], 'verbose_name': 'Enrollment Token', 'verbose_name_plural': 'Enrollment Tokens'},
        ),
        migrations.AddConstraint(
            model_name='enrollmenttoken',
            constraint=models.UniqueConstraint(fields=('policy', 'name'), name='unique_token_name_per_policy'),
        ),
    ]
