# Generated by Django 6.0 on 2026-03-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0009_connection_last_check_in_policy_jvm_options_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystore',
            name='revision_number',
            field=models.IntegerField(default=0, help_text='Revision number for this deployment'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='revision_number',
            field=models.IntegerField(default=0, help_text='Revision number for this deployment'),
        ),
    ]
