# Generated by Django 6.0 on 2026-03-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0011_keystore_kv_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='binary_path',
            field=models.CharField(default='/usr/share/logstash/bin', help_text='Path to Logstash binary directory', max_length=255),
        ),
    ]
