# Generated by Django 6.0.3 on 2026-03-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0012_policy_binary_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='status_blob',
            field=models.JSONField(blank=True, help_text='JSON blob containing agent health status information', null=True),
        ),
    ]
