# Generated by Django 6.0.3 on 2026-04-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0013_connection_status_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='pipeline_batch_delay',
            field=models.IntegerField(default=50, help_text='Batch delay in milliseconds'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='pipeline_batch_size',
            field=models.IntegerField(default=128, help_text='Maximum number of events per batch'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='pipeline_workers',
            field=models.IntegerField(default=1, help_text='Number of worker threads for pipeline execution'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='queue_checkpoint_writes',
            field=models.IntegerField(default=1024, help_text='Number of writes before checkpoint (for persisted queue)'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='queue_max_bytes',
            field=models.CharField(default='1gb', help_text='Maximum queue size (e.g., 1gb, 512mb)', max_length=20),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='queue_type',
            field=models.CharField(default='memory', help_text='Queue type (memory or persisted)', max_length=20),
        ),
    ]
