# Generated by Django 6.0.3 on 2026-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0014_pipeline_pipeline_batch_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='pipeline_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA256 hash of pipeline name + lscl + all settings, for agent change detection', max_length=64),
        ),
    ]
