# Generated by Django 6.0.3 on 2026-04-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0017_policy_keystore_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='last_deployed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful deployment', null=True),
        ),
    ]
