# Generated by Django 6.0.3 on 2026-04-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0018_policy_last_deployed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='restart_on_next_checkin',
            field=models.BooleanField(default=False, help_text='If true, instructs the agent to restart Logstash on its next check-in'),
        ),
    ]
