# Generated by Django 6.0.3 on 2026-04-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0019_connection_restart_on_next_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='no_input',
            field=models.BooleanField(default=False, help_text="True if the pipeline's input block contains no plugins"),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='non_reloadable',
            field=models.BooleanField(default=False, help_text='True if the pipeline contains a stdin input plugin (prevents hot-reload)'),
        ),
    ]
