# Generated by Django 6.0.3 on 2026-04-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0020_pipeline_no_input_pipeline_non_reloadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='desired_agent_version',
            field=models.CharField(blank=True, help_text='Desired LogstashAgent version for this connection (triggers upgrade on next check-in)', max_length=20, null=True),
        ),
    ]
