# Generated by Django 6.0.3 on 2026-07-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0021_connection_desired_agent_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystore',
            name='managed_by',
            field=models.CharField(choices=[('user', 'User'), ('snmp', 'SNMP'), ('library', 'Library')], default='user', help_text='Which subsystem owns this keystore entry (user, snmp, library)', max_length=20),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='managed_by',
            field=models.CharField(choices=[('user', 'User'), ('snmp', 'SNMP'), ('library', 'Library')], default='user', help_text='Which subsystem owns this pipeline (user, snmp, library)', max_length=20),
        ),
    ]
