# Generated by Django 6.0.3 on 2026-07-29 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0022_keystore_managed_by_pipeline_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='agent_api_port',
            field=models.PositiveIntegerField(blank=True, help_text='Agent FastAPI port for this connection (embedded 9500; simulate 9500+N)', null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='instance_id',
            field=models.PositiveIntegerField(blank=True, help_text='Simulate instance number N (paths under /opt/logstash-agent/simulate-N)', null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_selected_at',
            field=models.DateTimeField(blank=True, help_text='Last time this connection was selected as a sim target (sticky UX only)', null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='logstash_api_port',
            field=models.PositiveIntegerField(blank=True, help_text='Logstash HTTP API port for this connection (embedded 9560; simulate 9560+N)', null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='logstash_version_resolved',
            field=models.CharField(blank=True, default='', help_text='Logstash version reported by the agent (for sim target dropdown)', max_length=64),
        ),
        migrations.AddField(
            model_name='policy',
            name='agent_api_port',
            field=models.PositiveIntegerField(default=9500, help_text='Default LogstashAgent FastAPI port (simulate/embedded; live ports may be assigned at enroll)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='cloned_from',
            field=models.ForeignKey(blank=True, help_text='Source policy if this was cloned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='PipelineManager.policy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='data_path',
            field=models.CharField(blank=True, default='', help_text='Path to Logstash data directory (optional; simulate derives from instance)', max_length=255),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System-seeded policy (restricted delete / structural edit)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='keystore_env_file',
            field=models.CharField(blank=True, default='/etc/default/logstash', help_text='Env file path where LOGSTASH_KEYSTORE_PASS is written for systemd', max_length=512),
        ),
        migrations.AddField(
            model_name='policy',
            name='logstash_api_port',
            field=models.PositiveIntegerField(default=9560, help_text='Default Logstash HTTP API port (embedded 9560; simulate uses 9560+N at enroll)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='logstash_download_dir',
            field=models.CharField(blank=True, default='/opt/logstash-agent/logstash-versions', help_text='Directory for auto-downloaded Logstash versions', max_length=512),
        ),
        migrations.AddField(
            model_name='policy',
            name='logstash_source',
            field=models.CharField(choices=[('SYSTEM', 'System Logstash'), ('VERSION', 'Pinned version (download)')], default='SYSTEM', help_text='Where the simulate agent obtains the Logstash binary', max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='logstash_version',
            field=models.CharField(blank=True, default='', help_text='Pinned Logstash version when logstash_source=VERSION (e.g. 9.4.3)', max_length=32),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('SIMULATE', 'Simulate'), ('EMBEDDED', 'Embedded')], default='DEFAULT', help_text='Agent role this policy targets', max_length=20),
        ),
    ]
