# Generated by Django 6.0.3 on 2026-09-03 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipelineManager', '0027_packaged_managed_default_ports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Human-readable label for this token', max_length=100),
        ),
        migrations.AddField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(blank=True, db_index=True, help_text='Unhashed lookup key for admin tokens; null for agent keys', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User this API token acts as (admin tokens only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Connection this API key belongs to (agent keys only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='PipelineManager.connection'),
        ),
        # The four AlterFields below are unrelated pre-existing drift: help_text
        # was edited in 638acfb without regenerating a migration. They emit no
        # SQL, and absorbing them here stops the drift trailing into the next
        # unrelated migration.
        migrations.AlterField(
            model_name='connection',
            name='agent_api_port',
            field=models.PositiveIntegerField(blank=True, help_text='Agent FastAPI port for this connection (packaged 9550; managed 9550+N; simulate 9500+N; embedded 9500)', null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='logstash_api_port',
            field=models.PositiveIntegerField(blank=True, help_text='Logstash HTTP API port for this connection (packaged 9600; managed 9700+N; simulate 9560+N; embedded 9560)', null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='agent_api_port',
            field=models.PositiveIntegerField(default=9500, help_text='Policy default agent FastAPI port (Packaged 9550 as-is; Managed 9550+N; Simulate/Embedded 9500+N or 9500)'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='logstash_api_port',
            field=models.PositiveIntegerField(default=9560, help_text='Policy default Logstash HTTP API port (Packaged 9600 as-is; Managed 9700+N; Simulate/Embedded 9560+N or 9560)'),
        ),
    ]
