# Generated by Django 6.0 on 2026-02-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this credential', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this credential')),
                ('version', models.CharField(choices=[('1', 'SNMPv1'), ('2c', 'SNMPv2c'), ('3', 'SNMPv3')], default='2c', help_text='SNMP version (1, 2c, or 3)', max_length=2)),
                ('community', models.CharField(blank=True, default='public', help_text='Community string for SNMPv1/v2c (default: public)', max_length=255)),
                ('security_name', models.CharField(blank=True, help_text='SNMPv3 security name or user name', max_length=255)),
                ('security_level', models.CharField(blank=True, choices=[('noAuthNoPriv', 'No Authentication, No Privacy'), ('authNoPriv', 'Authentication, No Privacy'), ('authPriv', 'Authentication and Privacy')], help_text='SNMPv3 security level', max_length=20)),
                ('auth_protocol', models.CharField(blank=True, choices=[('md5', 'MD5'), ('sha', 'SHA'), ('sha2', 'SHA2'), ('hmac128sha224', 'HMAC128-SHA224'), ('hmac192sha256', 'HMAC192-SHA256'), ('hmac256sha384', 'HMAC256-SHA384'), ('hmac384sha512', 'HMAC384-SHA512')], help_text='SNMPv3 authentication protocol', max_length=20)),
                ('auth_pass', models.CharField(blank=True, help_text='SNMPv3 authentication passphrase or password', max_length=255)),
                ('priv_protocol', models.CharField(blank=True, choices=[('des', 'DES'), ('3des', '3DES'), ('aes', 'AES'), ('aes128', 'AES128'), ('aes192', 'AES192'), ('aes256', 'AES256'), ('aes256with3desKey', 'AES256 with 3DES Key')], help_text='SNMPv3 privacy/encryption protocol', max_length=20)),
                ('priv_pass', models.CharField(blank=True, help_text='SNMPv3 encryption password', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SNMP Credential',
                'verbose_name_plural': 'SNMP Credentials',
                'ordering': ['name'],
            },
        ),
    ]
