# Generated by Django 6.0 on 2026-02-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this network', max_length=255, unique=True)),
                ('network_range', models.CharField(help_text='Network in CIDR notation (e.g., 192.168.1.0/24)', max_length=50)),
                ('logstash_name', models.CharField(help_text='Name of the Logstash node that will monitor this network', max_length=255)),
                ('discovery_enabled', models.BooleanField(default=True, help_text='Enable automatic device discovery on this network')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SNMP Network',
                'verbose_name_plural': 'SNMP Networks',
                'ordering': ['name'],
            },
        ),
    ]
