# Generated by Django 6.0 on 2026-02-05 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNMP', '0002_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this device', max_length=255, unique=True)),
                ('ip_address', models.CharField(help_text='IP address or hostname of the device', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(blank=True, help_text='SNMP credential to use for this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='SNMP.credential')),
                ('network', models.ForeignKey(blank=True, help_text='Network this device belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='SNMP.network')),
            ],
            options={
                'verbose_name': 'SNMP Device',
                'verbose_name_plural': 'SNMP Devices',
                'ordering': ['name'],
            },
        ),
    ]
