# Generated by Django 6.0 on 2026-02-05 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_connection_api_key_alter_connection_password'),
        ('SNMP', '0003_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Logstash connection that will monitor this network', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snmp_networks', to='Core.connection'),
        ),
        migrations.AlterField(
            model_name='network',
            name='logstash_name',
            field=models.CharField(blank=True, help_text='Name of the Logstash node that will monitor this network (deprecated, use connection instead)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['name'], name='SNMP_device_name_087021_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['ip_address'], name='SNMP_device_ip_addr_6a90e5_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['-created_at'], name='SNMP_device_created_becb56_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['network', 'name'], name='SNMP_device_network_889f1c_idx'),
        ),
    ]
