
# Mode determines if the agent is used for simulating
# in LogstashUI, or for controlling an actual Logstash host
mode: host # simulation | host

# Only applies if mode 'mode' is set to simulation
simulation_mode: embedded # embedded | host


# Linux example, default
logstash_binary: /usr/share/logstash/bin/logstash
logstash_settings: /etc/logstash
logstash_log_path: /var/log/logstash