# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the Elastic License;
# you may not use this file except in compliance with the Elastic License.

"""
Django settings for logstashui project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, platform
from importlib.metadata import version, PackageNotFoundError
from Common.encryption import get_django_secret_key
from .config import CONFIG, merge_allowed_hosts
from .insecure_http import (
    force_http_origins,
    force_http_url,
    insecure_http,
    secure_cookies,
    tls_enabled,
    warn_if_enabled,
)
from .database import build_databases
from .logging_config import resolve_django_log_levels, resolve_log_level
from .paths import (
    resolve_data_dir,
    resolve_docs_dir,
    resolve_logs_dir,
    resolve_logstash_dir,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Project root is 2 levels up from BASE_DIR (src/logstashui/)
PROJECT_ROOT = BASE_DIR.parent.parent

# logstashui Runtime Configuration (environment variables; see LogstashUI.config)
LOGSTASHUI_CONFIG = CONFIG

# Runtime state (sqlite, tls, secrets). Outside src/ unless pytest.
# Env LOGSTASHUI_DATA_DIR overrides the default $(pwd)/logstashui_data.
# Docker/systemd set /var/lib/logstashui.
DATA_DIR = resolve_data_dir()
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Automatically generates and persists a unique key per deployment in DATA_DIR/.django_secret_key
# Can be overridden with SECRET_KEY environment variable
SECRET_KEY = get_django_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False in production via environment variable
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

# SECURITY WARNING: Set ALLOWED_HOSTS to your domain(s) in production
# Example: ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
ALLOWED_HOSTS = merge_allowed_hosts()


def _get_version():
    """Get version from installed package metadata or pyproject.toml"""
    try:
        return version("LogstashUI")
    except PackageNotFoundError:
        try:
            import tomllib

            pyproject_path = PROJECT_ROOT / "pyproject.toml"
            if pyproject_path.exists():
                with open(pyproject_path, "rb") as f:
                    pyproject_data = tomllib.load(f)
                    return pyproject_data.get("project", {}).get(
                        "version", "0.0.0+unknown"
                    )
        except Exception:
            pass
        return "0.0.0+unknown"


__VERSION__ = _get_version()
__PREFERRED_LS_AGENT_VERSION__ = "0.5.2"

# Application definition

INSTALLED_APPS = [
    # Shipped with Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Apps of logstashui
    "PipelineManager",
    "Management",
    "Utilities",
    "SNMP",
    "Monitoring",
    "Site",
    "Documentation",
    "AI",
    # Frameworks
    "django_htmx",
    "tailwind",
    "theme",  # Belongs to tailwind
]

TAILWIND_APP_NAME = "theme"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # Must precede CsrfViewMiddleware: it exempts verified API-token requests
    # from CSRF. Browser and agent traffic pass through untouched.
    "Common.middleware.ApiTokenCsrfMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Must follow AuthenticationMiddleware, which would otherwise overwrite
    # request.user with the lazy session user.
    "Common.middleware.ApiTokenUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "login_required.middleware.LoginRequiredMiddleware",
    "Common.middleware.SecurityHeadersMiddleware",
]

ROOT_URLCONF = "LogstashUI.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "Common.context_processors.version_update_info",
                "Common.context_processors.navigation_highlight",
                "Common.context_processors.experimental_mode",
            ],
        },
    },
]

WSGI_APPLICATION = "LogstashUI.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = build_databases(DATA_DIR)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_ROOT = DATA_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "Site/static",
]
_docs_images = resolve_docs_dir() / "images"
if _docs_images.is_dir():
    STATICFILES_DIRS.append(_docs_images)
elif (PROJECT_ROOT / "docs" / "images").is_dir():
    STATICFILES_DIRS.append(PROJECT_ROOT / "docs" / "images")

if platform.system() == "Windows":
    NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"
else:
    NPM_BIN_PATH = "npm"

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ["django_browser_reload"]
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]


NO_AUTH_MODE = LOGSTASHUI_CONFIG.get("no_auth", {}).get("enabled", False)

if NO_AUTH_MODE:
    import logging

    logging.getLogger(__name__).warning(
        "*** NO_AUTH MODE IS ENABLED — All authentication is bypassed. "
        "Do not use in production! ***"
    )
    _auth_idx = MIDDLEWARE.index(
        "django.contrib.auth.middleware.AuthenticationMiddleware"
    )
    MIDDLEWARE.insert(_auth_idx + 1, "Common.middleware.NoAuthMiddleware")

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/Management/Login/"
LOGIN_URL = "/Management/Login/"

LOGIN_REQUIRED_IGNORE_PATHS = [
    "/Management/Login/",
    "/Management/Logout/",
    "/static/",
    "/health/",
    "/.well-known/logstashui/ca.crt",
    "/ConnectionManager/StreamSimulate/",
    "/ConnectionManager/StreamSimulate",
    "/ConnectionManager/Enroll/",
    "/ConnectionManager/Enroll",
    "/ConnectionManager/CheckIn/",
    "/ConnectionManager/CheckIn",
    "/ConnectionManager/GetConfigChanges/",
    "/ConnectionManager/GetConfigChanges",
    "/ConnectionManager/IssueServerCert/",
    "/ConnectionManager/IssueServerCert",
    # Prefix match: covers /LogstashArtifact/<connection_id>/<filename>.
    # The view authenticates the agent key itself.
    "/ConnectionManager/LogstashArtifact/",
]

# Session Configuration
# Sessions expire after 24 hours of inactivity
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Reset timeout on every request (sliding window)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Allow persistent sessions

# Proxy/HTTPS settings for nginx reverse proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# CSRF Trusted Origins - configurable via environment variable
# For self-hosted deployments, users should set CSRF_TRUSTED_ORIGINS env var
# Example: CSRF_TRUSTED_ORIGINS=https://myserver.com,https://192.168.1.100
csrf_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(",") if origin.strip()]
else:
    # Default for local development
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8080",
        "http://127.0.0.1:8080",
        "https://localhost",
        "https://127.0.0.1",
    ]

INSECURE_HTTP = insecure_http()
if INSECURE_HTTP:
    CSRF_TRUSTED_ORIGINS = force_http_origins(CSRF_TRUSTED_ORIGINS, enabled=True)

# Security Headers
# These settings protect against common web vulnerabilities
# Only enforce in production (when DEBUG=False)
_tls_env = os.environ.get("LOGSTASHUI_TLS", "true")
TLS_ENABLED = tls_enabled(tls_env=_tls_env, insecure=INSECURE_HTTP)
if INSECURE_HTTP:
    warn_if_enabled()

_secure_cookies = secure_cookies(debug=DEBUG, insecure=INSECURE_HTTP)

if not DEBUG:
    SESSION_COOKIE_SECURE = _secure_cookies
    CSRF_COOKIE_SECURE = _secure_cookies
    if _secure_cookies:
        SECURE_HSTS_SECONDS = 31536000  # 1 year
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
    else:
        SECURE_HSTS_SECONDS = 0
        SECURE_HSTS_INCLUDE_SUBDOMAINS = False
        SECURE_HSTS_PRELOAD = False
    SECURE_SSL_REDIRECT = TLS_ENABLED
    X_FRAME_OPTIONS = "DENY"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
else:
    # Development mode - allow HTTP for local testing
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    X_FRAME_OPTIONS = "SAMEORIGIN"

# logstashagent Configuration
# URL for the logstashagent API (HTTPS direct; no nginx).
# Override with LOGSTASH_AGENT_URL. Compose sets https://logstashagent:9500.
if DEBUG:
    LOGSTASH_AGENT_URL = os.environ.get("LOGSTASH_AGENT_URL", "http://127.0.0.1:9500")
else:
    LOGSTASH_AGENT_URL = os.environ.get(
        "LOGSTASH_AGENT_URL", "https://logstashagent:9500"
    )
LOGSTASH_AGENT_URL = force_http_url(LOGSTASH_AGENT_URL, enabled=INSECURE_HTTP)

# Logstash tarball proxy
# Cache of Logstash release tarballs served to agents whose policy sets
# logstash_via_ui. See PipelineManager/artifacts.py.
LOGSTASH_DIR = resolve_logstash_dir(DATA_DIR)
LOGSTASH_DIR.mkdir(parents=True, exist_ok=True)

# Upstream fetches in flight cluster-wide, counted in the DB (the only state
# shared between gunicorn workers -- there is no CACHES backend configured).
LOGSTASH_ARTIFACT_MAX_UPSTREAM = int(
    os.environ.get("LOGSTASHUI_ARTIFACT_MAX_UPSTREAM", "2")
)
# Concurrent agent downloads *per worker*. Effective total is this value times
# LOGSTASHUI_WORKERS. Deliberately not a global divided by worker count: that
# truncates to zero and makes the knob lie.
LOGSTASH_ARTIFACT_MAX_SERVE_PER_WORKER = int(
    os.environ.get("LOGSTASHUI_ARTIFACT_MAX_SERVE_PER_WORKER", "4")
)
LOGSTASH_ARTIFACT_DEFAULT_BASE_URL = "https://artifacts.elastic.co/downloads/logstash"

# Logging Configuration
# https://docs.djangoproject.com/en/5.2/topics/logging/

# Ensure logs directory exists (LOGSTASHUI_LOGS_DIR / DATA_DIR/logs)
LOGS_DIR = resolve_logs_dir(DATA_DIR)
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGSTASHUI_LOG_LEVEL = resolve_log_level(
    "LOGSTASHUI_LOG_LEVEL",
    default="DEBUG" if DEBUG else "INFO",
)
DJANGO_LOGGER_LEVEL, DJANGO_REQUEST_LOG_LEVEL = resolve_django_log_levels()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name} {module}.{funcName}: {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "level": LOGSTASHUI_LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": LOGSTASHUI_LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "logstashui.log",
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": DJANGO_LOGGER_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": DJANGO_REQUEST_LOG_LEVEL,
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": LOGSTASHUI_LOG_LEVEL,
    },
}
