"""
Django settings for logstashui project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, platform
from importlib.metadata import version, PackageNotFoundError
from Common.encryption import get_django_secret_key
from .config import CONFIG

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Project root is 2 levels up from BASE_DIR (src/logstashui/)
PROJECT_ROOT = BASE_DIR.parent.parent

# logstashui Runtime Configuration
# Loaded from YAML file specified in LOGSTASHUI_CONFIG environment variable
# Falls back to DEFAULT_CONFIG if not specified
LOGSTASHUI_CONFIG = CONFIG

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Automatically generates and persists a unique key per deployment in data/.django_secret_key
# Can be overridden with SECRET_KEY environment variable
SECRET_KEY = get_django_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False in production via environment variable
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# SECURITY WARNING: Set ALLOWED_HOSTS to your domain(s) in production
# Example: ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

def _get_version():
    """Get version from installed package metadata or pyproject.toml"""
    try:
        return version("LogstashUI")
    except PackageNotFoundError:
        try:
            import tomllib
            pyproject_path = PROJECT_ROOT / "pyproject.toml"
            if pyproject_path.exists():
                with open(pyproject_path, "rb") as f:
                    pyproject_data = tomllib.load(f)
                    return pyproject_data.get("project", {}).get("version", "0.0.0+unknown")
        except Exception:
            pass
        return "0.0.0+unknown"

__VERSION__ = _get_version()

# Application definition

INSTALLED_APPS = [
    # Shipped with Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps of logstashui
    'PipelineManager',
    'Management',
    'Utilities',
    'SNMP',
    'Monitoring',
    'Site',

    # Frameworks
    'django_htmx',
    'tailwind',
    'theme' # Belongs to tailwind
]

TAILWIND_APP_NAME = "theme"




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'login_required.middleware.LoginRequiredMiddleware',
    'Common.middleware.SecurityHeadersMiddleware',

]

ROOT_URLCONF = 'LogstashUI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Common.context_processors.version_update_info',
                'Common.context_processors.navigation_highlight',
            ],
        },
    },
]

WSGI_APPLICATION = 'LogstashUI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "Site/static"
]

if platform.system() == "Windows":
    NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"
else:
    NPM_BIN_PATH = "npm"

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ['django_browser_reload']
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]


LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/Management/Login/"
LOGIN_URL = "/Management/Login/"

LOGIN_REQUIRED_IGNORE_PATHS = [
    "/Management/Login/",
    "/Management/Logout/",
    "/static/",
    "/health/",
    "/ConnectionManager/StreamSimulate/",
    "/ConnectionManager/StreamSimulate",
    "/ConnectionManager/Enroll/",
    "/ConnectionManager/Enroll",
    "/ConnectionManager/CheckIn/",
    "/ConnectionManager/CheckIn",
    "/ConnectionManager/GetConfigChanges/",
    "/ConnectionManager/GetConfigChanges"
]

# Session Configuration
# Sessions expire after 24 hours of inactivity
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Reset timeout on every request (sliding window)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Allow persistent sessions

# Proxy/HTTPS settings for nginx reverse proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# CSRF Trusted Origins - configurable via environment variable
# For self-hosted deployments, users should set CSRF_TRUSTED_ORIGINS env var
# Example: CSRF_TRUSTED_ORIGINS=https://myserver.com,https://192.168.1.100
csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',')]
else:
    # Default for local development
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8080',
        'http://127.0.0.1:8080',
        'https://localhost',
        'https://127.0.0.1',
    ]

# Security Headers
# These settings protect against common web vulnerabilities
# Only enforce in production (when DEBUG=False)
if not DEBUG:
    # Ensure cookies are only sent over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HTTP Strict Transport Security (HSTS)
    # Tells browsers to only access the site via HTTPS for the next year
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Redirect all HTTP requests to HTTPS at Django level
    # Note: nginx already does this, but this adds defense in depth
    SECURE_SSL_REDIRECT = True
    
    # Prevent the site from being embedded in iframes (clickjacking protection)
    X_FRAME_OPTIONS = 'DENY'
    
    # Prevent browsers from guessing content types
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # Enable browser's XSS filtering
    SECURE_BROWSER_XSS_FILTER = True
else:
    # Development mode - allow HTTP for local testing
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    X_FRAME_OPTIONS = 'SAMEORIGIN'

# logstashagent Configuration
# URL for the logstashagent API
# Can be overridden with LOGSTASH_AGENT_URL environment variable
# 
# Routing based on simulation mode:
# - Host mode: Direct to host.docker.internal:9501 (native agent on host)
# - Embedded mode: Via nginx proxy to logstashagent:9500 (container)
if DEBUG:
    # Development: Direct HTTP connection (for local testing without containers)
    LOGSTASH_AGENT_URL = os.environ.get('LOGSTASH_AGENT_URL', 'http://127.0.0.1:9500')
else:
    # Production: Check simulation mode from config
    simulation_mode = LOGSTASHUI_CONFIG.get('simulation', {}).get('mode', 'embedded')
    
    if simulation_mode == 'host':
        # Host mode: Agent runs natively on host port 9501
        # Use HTTP to host.docker.internal (no SSL for internal communication)
        LOGSTASH_AGENT_URL = os.environ.get('LOGSTASH_AGENT_URL', 'http://host.docker.internal:9501')
    else:
        # Embedded mode: Agent runs in container, accessed via nginx proxy
        LOGSTASH_AGENT_URL = os.environ.get('LOGSTASH_AGENT_URL', 'https://nginx:9500')

# Logging Configuration
# https://docs.djangoproject.com/en/5.2/topics/logging/

# Ensure logs directory exists
LOGS_DIR = BASE_DIR / 'data' / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module}.{funcName}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'logstashui.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
}