-- Snapshot of LogstashUI 0.5.2 `migrate` DDL on PostgreSQL 16.
-- Generated with pg_dump --schema-only. Do NOT apply this instead of
-- `logstashui manage migrate --noinput`. It will go stale with new migrations.
-- Create the empty database first (see create-postgresql.sql).

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Management_userprofile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Management_userprofile" (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: Management_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Management_userprofile" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Management_userprofile_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PipelineManager_apikey; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PipelineManager_apikey" (
    id bigint NOT NULL,
    api_key character varying(512) NOT NULL,
    connection_id bigint NOT NULL
);


--
-- Name: PipelineManager_apikey_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PipelineManager_apikey" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PipelineManager_apikey_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PipelineManager_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PipelineManager_connection" (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    connection_type character varying(20) NOT NULL,
    host character varying(255),
    port integer,
    username character varying(100),
    password character varying(512),
    ssh_key text,
    cloud_id character varying(255),
    cloud_url character varying(200),
    api_key character varying(512),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    policy_id bigint,
    agent_id character varying(255),
    last_check_in timestamp with time zone,
    status_blob jsonb,
    restart_on_next_checkin boolean NOT NULL,
    desired_agent_version character varying(20),
    agent_api_port integer,
    instance_id integer,
    last_selected_at timestamp with time zone,
    logstash_api_port integer,
    logstash_version_resolved character varying(64) NOT NULL,
    CONSTRAINT "PipelineManager_connection_agent_api_port_check" CHECK ((agent_api_port >= 0)),
    CONSTRAINT "PipelineManager_connection_instance_id_check" CHECK ((instance_id >= 0)),
    CONSTRAINT "PipelineManager_connection_logstash_api_port_check" CHECK ((logstash_api_port >= 0)),
    CONSTRAINT "PipelineManager_connection_port_check" CHECK ((port >= 0))
);


--
-- Name: PipelineManager_connection_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PipelineManager_connection" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PipelineManager_connection_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PipelineManager_enrollmenttoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PipelineManager_enrollmenttoken" (
    id bigint NOT NULL,
    token character varying(512) NOT NULL,
    policy_id bigint NOT NULL,
    name character varying(100) NOT NULL
);


--
-- Name: PipelineManager_enrollmenttoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PipelineManager_enrollmenttoken" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PipelineManager_enrollmenttoken_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PipelineManager_keystore; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PipelineManager_keystore" (
    id bigint NOT NULL,
    key_name character varying(100) NOT NULL,
    key_value character varying(512) NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    policy_id bigint NOT NULL,
    revision_number integer NOT NULL,
    kv_hash character varying(64) NOT NULL,
    managed_by character varying(20) NOT NULL
);


--
-- Name: PipelineManager_keystore_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PipelineManager_keystore" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PipelineManager_keystore_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PipelineManager_pipeline; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PipelineManager_pipeline" (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    lscl text NOT NULL,
    lscl_hash character varying(64),
    last_updated timestamp with time zone NOT NULL,
    policy_id bigint NOT NULL,
    revision_number integer NOT NULL,
    pipeline_batch_delay integer NOT NULL,
    pipeline_batch_size integer NOT NULL,
    pipeline_workers integer NOT NULL,
    queue_checkpoint_writes integer NOT NULL,
    queue_max_bytes character varying(20) NOT NULL,
    queue_type character varying(20) NOT NULL,
    pipeline_hash character varying(64) NOT NULL,
    no_input boolean NOT NULL,
    non_reloadable boolean NOT NULL,
    managed_by character varying(20) NOT NULL
);


--
-- Name: PipelineManager_pipeline_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PipelineManager_pipeline" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PipelineManager_pipeline_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PipelineManager_policy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PipelineManager_policy" (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    settings_path character varying(255) NOT NULL,
    logs_path character varying(255) NOT NULL,
    logstash_yml text NOT NULL,
    jvm_options text NOT NULL,
    log4j2_properties text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    current_revision_number integer NOT NULL,
    has_undeployed_changes boolean NOT NULL,
    jvm_options_hash character varying(64) NOT NULL,
    log4j2_properties_hash character varying(64) NOT NULL,
    logstash_yml_hash character varying(64) NOT NULL,
    binary_path character varying(255) NOT NULL,
    keystore_password character varying(512),
    keystore_password_hash character varying(64) NOT NULL,
    last_deployed_at timestamp with time zone,
    agent_api_port integer NOT NULL,
    cloned_from_id bigint,
    data_path character varying(255) NOT NULL,
    is_system boolean NOT NULL,
    keystore_env_file character varying(512) NOT NULL,
    logstash_api_port integer NOT NULL,
    logstash_download_dir character varying(512) NOT NULL,
    logstash_source character varying(20) NOT NULL,
    logstash_version character varying(32) NOT NULL,
    policy_type character varying(20) NOT NULL,
    CONSTRAINT "PipelineManager_policy_agent_api_port_check" CHECK ((agent_api_port >= 0)),
    CONSTRAINT "PipelineManager_policy_logstash_api_port_check" CHECK ((logstash_api_port >= 0))
);


--
-- Name: PipelineManager_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PipelineManager_policy" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PipelineManager_policy_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PipelineManager_revision; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PipelineManager_revision" (
    id bigint NOT NULL,
    revision_number integer NOT NULL,
    snapshot_json jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by character varying(150) NOT NULL,
    policy_id bigint NOT NULL
);


--
-- Name: PipelineManager_revision_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PipelineManager_revision" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PipelineManager_revision_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SNMP_credential; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."SNMP_credential" (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    version character varying(2) NOT NULL,
    community character varying(255) NOT NULL,
    security_name character varying(255) NOT NULL,
    security_level character varying(20) NOT NULL,
    auth_protocol character varying(20) NOT NULL,
    auth_pass character varying(255) NOT NULL,
    priv_protocol character varying(20) NOT NULL,
    priv_pass character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: SNMP_credential_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."SNMP_credential" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SNMP_credential_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SNMP_device; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."SNMP_device" (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    ip_address character varying(255),
    port integer NOT NULL,
    retries integer NOT NULL,
    timeout integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    credential_id bigint,
    network_id bigint,
    device_template_id bigint,
    hostname character varying(255),
    building character varying(255),
    latitude numeric(15,10),
    longitude numeric(15,10),
    metadata jsonb NOT NULL,
    room character varying(255),
    site character varying(255)
);


--
-- Name: SNMP_device_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."SNMP_device" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SNMP_device_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SNMP_devicetemplate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."SNMP_devicetemplate" (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    vendor character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    matching_rules jsonb NOT NULL,
    official boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product character varying(100) NOT NULL,
    type character varying(100) NOT NULL,
    official_key character varying(255)
);


--
-- Name: SNMP_devicetemplate_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."SNMP_devicetemplate" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SNMP_devicetemplate_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SNMP_devicetemplate_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."SNMP_devicetemplate_profiles" (
    id bigint NOT NULL,
    devicetemplate_id bigint NOT NULL,
    profile_id bigint NOT NULL
);


--
-- Name: SNMP_devicetemplate_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."SNMP_devicetemplate_profiles" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SNMP_devicetemplate_profiles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SNMP_network; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."SNMP_network" (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    network_range character varying(50) NOT NULL,
    discovery_enabled boolean NOT NULL,
    traps_enabled boolean NOT NULL,
    "interval" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    connection_id bigint,
    credential_id bigint,
    discovery_credential_id bigint,
    namespace character varying(100) NOT NULL,
    namespace_from_device_template boolean NOT NULL,
    agent_connection_id bigint,
    deployment_mode character varying(20) NOT NULL,
    credential_mode character varying(20) NOT NULL,
    CONSTRAINT "SNMP_network_interval_check" CHECK (("interval" >= 0))
);


--
-- Name: SNMP_network_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."SNMP_network" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SNMP_network_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SNMP_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."SNMP_profile" (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    profile_data jsonb NOT NULL,
    description text NOT NULL,
    vendor character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product character varying(100) NOT NULL,
    normalizers jsonb NOT NULL,
    official_key character varying(255)
);


--
-- Name: SNMP_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."SNMP_profile" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SNMP_profile_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    id bigint NOT NULL,
    experimental_mode boolean NOT NULL,
    agent_ui_url character varying(512) NOT NULL
);


--
-- Name: settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: snmp_deployment_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.snmp_deployment_state (
    id bigint NOT NULL,
    last_deployment timestamp with time zone,
    last_config_change timestamp with time zone
);


--
-- Name: snmp_deployment_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.snmp_deployment_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.snmp_deployment_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Management_userprofile Management_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Management_userprofile"
    ADD CONSTRAINT "Management_userprofile_pkey" PRIMARY KEY (id);


--
-- Name: Management_userprofile Management_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Management_userprofile"
    ADD CONSTRAINT "Management_userprofile_user_id_key" UNIQUE (user_id);


--
-- Name: PipelineManager_apikey PipelineManager_apikey_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_apikey"
    ADD CONSTRAINT "PipelineManager_apikey_pkey" PRIMARY KEY (id);


--
-- Name: PipelineManager_connection PipelineManager_connection_agent_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_connection"
    ADD CONSTRAINT "PipelineManager_connection_agent_id_key" UNIQUE (agent_id);


--
-- Name: PipelineManager_connection PipelineManager_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_connection"
    ADD CONSTRAINT "PipelineManager_connection_pkey" PRIMARY KEY (id);


--
-- Name: PipelineManager_enrollmenttoken PipelineManager_enrollmenttoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_enrollmenttoken"
    ADD CONSTRAINT "PipelineManager_enrollmenttoken_pkey" PRIMARY KEY (id);


--
-- Name: PipelineManager_keystore PipelineManager_keystore_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_keystore"
    ADD CONSTRAINT "PipelineManager_keystore_pkey" PRIMARY KEY (id);


--
-- Name: PipelineManager_pipeline PipelineManager_pipeline_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_pipeline"
    ADD CONSTRAINT "PipelineManager_pipeline_pkey" PRIMARY KEY (id);


--
-- Name: PipelineManager_policy PipelineManager_policy_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_policy"
    ADD CONSTRAINT "PipelineManager_policy_name_key" UNIQUE (name);


--
-- Name: PipelineManager_policy PipelineManager_policy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_policy"
    ADD CONSTRAINT "PipelineManager_policy_pkey" PRIMARY KEY (id);


--
-- Name: PipelineManager_revision PipelineManager_revision_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_revision"
    ADD CONSTRAINT "PipelineManager_revision_pkey" PRIMARY KEY (id);


--
-- Name: SNMP_credential SNMP_credential_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_credential"
    ADD CONSTRAINT "SNMP_credential_name_key" UNIQUE (name);


--
-- Name: SNMP_credential SNMP_credential_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_credential"
    ADD CONSTRAINT "SNMP_credential_pkey" PRIMARY KEY (id);


--
-- Name: SNMP_device SNMP_device_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_device"
    ADD CONSTRAINT "SNMP_device_name_key" UNIQUE (name);


--
-- Name: SNMP_device SNMP_device_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_device"
    ADD CONSTRAINT "SNMP_device_pkey" PRIMARY KEY (id);


--
-- Name: SNMP_devicetemplate SNMP_devicetemplate_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_devicetemplate"
    ADD CONSTRAINT "SNMP_devicetemplate_name_key" UNIQUE (name);


--
-- Name: SNMP_devicetemplate SNMP_devicetemplate_official_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_devicetemplate"
    ADD CONSTRAINT "SNMP_devicetemplate_official_key_key" UNIQUE (official_key);


--
-- Name: SNMP_devicetemplate SNMP_devicetemplate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_devicetemplate"
    ADD CONSTRAINT "SNMP_devicetemplate_pkey" PRIMARY KEY (id);


--
-- Name: SNMP_devicetemplate_profiles SNMP_devicetemplate_prof_devicetemplate_id_profil_fb6396a5_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_devicetemplate_profiles"
    ADD CONSTRAINT "SNMP_devicetemplate_prof_devicetemplate_id_profil_fb6396a5_uniq" UNIQUE (devicetemplate_id, profile_id);


--
-- Name: SNMP_devicetemplate_profiles SNMP_devicetemplate_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_devicetemplate_profiles"
    ADD CONSTRAINT "SNMP_devicetemplate_profiles_pkey" PRIMARY KEY (id);


--
-- Name: SNMP_network SNMP_network_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_network"
    ADD CONSTRAINT "SNMP_network_name_key" UNIQUE (name);


--
-- Name: SNMP_network SNMP_network_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_network"
    ADD CONSTRAINT "SNMP_network_pkey" PRIMARY KEY (id);


--
-- Name: SNMP_profile SNMP_profile_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_profile"
    ADD CONSTRAINT "SNMP_profile_name_key" UNIQUE (name);


--
-- Name: SNMP_profile SNMP_profile_official_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_profile"
    ADD CONSTRAINT "SNMP_profile_official_key_key" UNIQUE (official_key);


--
-- Name: SNMP_profile SNMP_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_profile"
    ADD CONSTRAINT "SNMP_profile_pkey" PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (id);


--
-- Name: snmp_deployment_state snmp_deployment_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_deployment_state
    ADD CONSTRAINT snmp_deployment_state_pkey PRIMARY KEY (id);


--
-- Name: PipelineManager_keystore unique_key_per_policy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_keystore"
    ADD CONSTRAINT unique_key_per_policy UNIQUE (policy_id, key_name);


--
-- Name: PipelineManager_pipeline unique_pipeline_per_policy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_pipeline"
    ADD CONSTRAINT unique_pipeline_per_policy UNIQUE (policy_id, name);


--
-- Name: PipelineManager_revision unique_revision_per_policy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_revision"
    ADD CONSTRAINT unique_revision_per_policy UNIQUE (policy_id, revision_number);


--
-- Name: PipelineManager_enrollmenttoken unique_token_name_per_policy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_enrollmenttoken"
    ADD CONSTRAINT unique_token_name_per_policy UNIQUE (policy_id, name);


--
-- Name: PipelineManager_apikey_connection_id_27156847; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "PipelineManager_apikey_connection_id_27156847" ON public."PipelineManager_apikey" USING btree (connection_id);


--
-- Name: PipelineManager_connection_agent_id_d5ec5cd5_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "PipelineManager_connection_agent_id_d5ec5cd5_like" ON public."PipelineManager_connection" USING btree (agent_id varchar_pattern_ops);


--
-- Name: PipelineManager_connection_policy_id_819d316d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "PipelineManager_connection_policy_id_819d316d" ON public."PipelineManager_connection" USING btree (policy_id);


--
-- Name: PipelineManager_enrollmenttoken_policy_id_355d6dca; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "PipelineManager_enrollmenttoken_policy_id_355d6dca" ON public."PipelineManager_enrollmenttoken" USING btree (policy_id);


--
-- Name: PipelineManager_keystore_policy_id_6309b699; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "PipelineManager_keystore_policy_id_6309b699" ON public."PipelineManager_keystore" USING btree (policy_id);


--
-- Name: PipelineManager_pipeline_policy_id_7c3a6fd9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "PipelineManager_pipeline_policy_id_7c3a6fd9" ON public."PipelineManager_pipeline" USING btree (policy_id);


--
-- Name: PipelineManager_policy_cloned_from_id_4177e74a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "PipelineManager_policy_cloned_from_id_4177e74a" ON public."PipelineManager_policy" USING btree (cloned_from_id);


--
-- Name: PipelineManager_policy_name_ec6c8a56_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "PipelineManager_policy_name_ec6c8a56_like" ON public."PipelineManager_policy" USING btree (name varchar_pattern_ops);


--
-- Name: PipelineManager_revision_policy_id_99e7d146; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "PipelineManager_revision_policy_id_99e7d146" ON public."PipelineManager_revision" USING btree (policy_id);


--
-- Name: SNMP_credential_name_2e8e0977_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_credential_name_2e8e0977_like" ON public."SNMP_credential" USING btree (name varchar_pattern_ops);


--
-- Name: SNMP_device_created_becb56_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_device_created_becb56_idx" ON public."SNMP_device" USING btree (created_at DESC);


--
-- Name: SNMP_device_credential_id_f229ff4e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_device_credential_id_f229ff4e" ON public."SNMP_device" USING btree (credential_id);


--
-- Name: SNMP_device_device_template_id_ca143332; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_device_device_template_id_ca143332" ON public."SNMP_device" USING btree (device_template_id);


--
-- Name: SNMP_device_hostnam_fae88a_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_device_hostnam_fae88a_idx" ON public."SNMP_device" USING btree (hostname);


--
-- Name: SNMP_device_ip_addr_6a90e5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_device_ip_addr_6a90e5_idx" ON public."SNMP_device" USING btree (ip_address);


--
-- Name: SNMP_device_name_087021_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_device_name_087021_idx" ON public."SNMP_device" USING btree (name);


--
-- Name: SNMP_device_name_e0c9483b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_device_name_e0c9483b_like" ON public."SNMP_device" USING btree (name varchar_pattern_ops);


--
-- Name: SNMP_device_network_889f1c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_device_network_889f1c_idx" ON public."SNMP_device" USING btree (network_id, name);


--
-- Name: SNMP_device_network_id_4dea94fa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_device_network_id_4dea94fa" ON public."SNMP_device" USING btree (network_id);


--
-- Name: SNMP_devicetemplate_name_9c02299b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_devicetemplate_name_9c02299b_like" ON public."SNMP_devicetemplate" USING btree (name varchar_pattern_ops);


--
-- Name: SNMP_devicetemplate_official_key_65a0ae02_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_devicetemplate_official_key_65a0ae02_like" ON public."SNMP_devicetemplate" USING btree (official_key varchar_pattern_ops);


--
-- Name: SNMP_devicetemplate_profiles_devicetemplate_id_da70425d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_devicetemplate_profiles_devicetemplate_id_da70425d" ON public."SNMP_devicetemplate_profiles" USING btree (devicetemplate_id);


--
-- Name: SNMP_devicetemplate_profiles_profile_id_4cb23513; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_devicetemplate_profiles_profile_id_4cb23513" ON public."SNMP_devicetemplate_profiles" USING btree (profile_id);


--
-- Name: SNMP_network_agent_connection_id_cf646bb5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_network_agent_connection_id_cf646bb5" ON public."SNMP_network" USING btree (agent_connection_id);


--
-- Name: SNMP_network_connection_id_432a2f88; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_network_connection_id_432a2f88" ON public."SNMP_network" USING btree (connection_id);


--
-- Name: SNMP_network_credential_id_3b15dfc1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_network_credential_id_3b15dfc1" ON public."SNMP_network" USING btree (credential_id);


--
-- Name: SNMP_network_discovery_credential_id_d9229589; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_network_discovery_credential_id_d9229589" ON public."SNMP_network" USING btree (discovery_credential_id);


--
-- Name: SNMP_network_name_83546472_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_network_name_83546472_like" ON public."SNMP_network" USING btree (name varchar_pattern_ops);


--
-- Name: SNMP_profile_name_8a9d3c9d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_profile_name_8a9d3c9d_like" ON public."SNMP_profile" USING btree (name varchar_pattern_ops);


--
-- Name: SNMP_profile_official_key_de922dd3_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "SNMP_profile_official_key_de922dd3_like" ON public."SNMP_profile" USING btree (official_key varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: Management_userprofile Management_userprofile_user_id_70f1a900_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Management_userprofile"
    ADD CONSTRAINT "Management_userprofile_user_id_70f1a900_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PipelineManager_apikey PipelineManager_apik_connection_id_27156847_fk_PipelineM; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_apikey"
    ADD CONSTRAINT "PipelineManager_apik_connection_id_27156847_fk_PipelineM" FOREIGN KEY (connection_id) REFERENCES public."PipelineManager_connection"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PipelineManager_connection PipelineManager_conn_policy_id_819d316d_fk_PipelineM; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_connection"
    ADD CONSTRAINT "PipelineManager_conn_policy_id_819d316d_fk_PipelineM" FOREIGN KEY (policy_id) REFERENCES public."PipelineManager_policy"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PipelineManager_enrollmenttoken PipelineManager_enro_policy_id_355d6dca_fk_PipelineM; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_enrollmenttoken"
    ADD CONSTRAINT "PipelineManager_enro_policy_id_355d6dca_fk_PipelineM" FOREIGN KEY (policy_id) REFERENCES public."PipelineManager_policy"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PipelineManager_keystore PipelineManager_keys_policy_id_6309b699_fk_PipelineM; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_keystore"
    ADD CONSTRAINT "PipelineManager_keys_policy_id_6309b699_fk_PipelineM" FOREIGN KEY (policy_id) REFERENCES public."PipelineManager_policy"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PipelineManager_pipeline PipelineManager_pipe_policy_id_7c3a6fd9_fk_PipelineM; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_pipeline"
    ADD CONSTRAINT "PipelineManager_pipe_policy_id_7c3a6fd9_fk_PipelineM" FOREIGN KEY (policy_id) REFERENCES public."PipelineManager_policy"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PipelineManager_policy PipelineManager_poli_cloned_from_id_4177e74a_fk_PipelineM; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_policy"
    ADD CONSTRAINT "PipelineManager_poli_cloned_from_id_4177e74a_fk_PipelineM" FOREIGN KEY (cloned_from_id) REFERENCES public."PipelineManager_policy"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PipelineManager_revision PipelineManager_revi_policy_id_99e7d146_fk_PipelineM; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PipelineManager_revision"
    ADD CONSTRAINT "PipelineManager_revi_policy_id_99e7d146_fk_PipelineM" FOREIGN KEY (policy_id) REFERENCES public."PipelineManager_policy"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SNMP_device SNMP_device_credential_id_f229ff4e_fk_SNMP_credential_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_device"
    ADD CONSTRAINT "SNMP_device_credential_id_f229ff4e_fk_SNMP_credential_id" FOREIGN KEY (credential_id) REFERENCES public."SNMP_credential"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SNMP_device SNMP_device_device_template_id_ca143332_fk_SNMP_devi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_device"
    ADD CONSTRAINT "SNMP_device_device_template_id_ca143332_fk_SNMP_devi" FOREIGN KEY (device_template_id) REFERENCES public."SNMP_devicetemplate"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SNMP_device SNMP_device_network_id_4dea94fa_fk_SNMP_network_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_device"
    ADD CONSTRAINT "SNMP_device_network_id_4dea94fa_fk_SNMP_network_id" FOREIGN KEY (network_id) REFERENCES public."SNMP_network"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SNMP_devicetemplate_profiles SNMP_devicetemplate__devicetemplate_id_da70425d_fk_SNMP_devi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_devicetemplate_profiles"
    ADD CONSTRAINT "SNMP_devicetemplate__devicetemplate_id_da70425d_fk_SNMP_devi" FOREIGN KEY (devicetemplate_id) REFERENCES public."SNMP_devicetemplate"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SNMP_devicetemplate_profiles SNMP_devicetemplate__profile_id_4cb23513_fk_SNMP_prof; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_devicetemplate_profiles"
    ADD CONSTRAINT "SNMP_devicetemplate__profile_id_4cb23513_fk_SNMP_prof" FOREIGN KEY (profile_id) REFERENCES public."SNMP_profile"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SNMP_network SNMP_network_agent_connection_id_cf646bb5_fk_PipelineM; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_network"
    ADD CONSTRAINT "SNMP_network_agent_connection_id_cf646bb5_fk_PipelineM" FOREIGN KEY (agent_connection_id) REFERENCES public."PipelineManager_connection"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SNMP_network SNMP_network_connection_id_432a2f88_fk_PipelineM; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_network"
    ADD CONSTRAINT "SNMP_network_connection_id_432a2f88_fk_PipelineM" FOREIGN KEY (connection_id) REFERENCES public."PipelineManager_connection"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SNMP_network SNMP_network_credential_id_3b15dfc1_fk_SNMP_credential_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_network"
    ADD CONSTRAINT "SNMP_network_credential_id_3b15dfc1_fk_SNMP_credential_id" FOREIGN KEY (credential_id) REFERENCES public."SNMP_credential"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SNMP_network SNMP_network_discovery_credential_d9229589_fk_SNMP_cred; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SNMP_network"
    ADD CONSTRAINT "SNMP_network_discovery_credential_d9229589_fk_SNMP_cred" FOREIGN KEY (discovery_credential_id) REFERENCES public."SNMP_credential"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


