#Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
#or more contributor license agreements. Licensed under the Elastic License;
#you may not use this file except in compliance with the Elastic License.

"""
Django management command to generate the LLM context file for SNMP template
and profile generation.

Reads all official device templates and profiles from the bundled JSON files and
writes a single Markdown file that can be fed verbatim to an LLM as context.

The output file is committed to the repository and updated whenever official
profiles or device templates are added or changed. Re-run this command any time
you modify files under:
    SNMP/data/official_profiles/
    SNMP/data/official_device_templates/

Usage:
    uv run python manage.py generate_template_profile_context
    uv run python manage.py generate_template_profile_context --output path/to/file.md

Output: SNMP/data/template_profile_context.md  (default)
"""

import json
import os
from django.conf import settings
from django.core.management.base import BaseCommand

_INTERNAL_KEYS = {'official_key', 'type'}


def _load_json_dir(dirpath):
    """
    Load all *.json files from *dirpath*, sorted by filename.
    Returns a list of (filename_without_extension, parsed_dict) tuples.
    Silently skips files that cannot be parsed.
    """
    results = []
    if not os.path.isdir(dirpath):
        return results
    for fname in sorted(os.listdir(dirpath)):
        if not fname.endswith('.json'):
            continue
        fpath = os.path.join(dirpath, fname)
        try:
            with open(fpath, 'r', encoding='utf-8') as fh:
                data = json.load(fh)
            results.append((fname[:-5], data))
        except Exception as exc:
            pass
    return results


def _strip_internal(d):
    """Return a copy of *d* with internal-only keys removed."""
    return {k: v for k, v in d.items() if k not in _INTERNAL_KEYS}


def _json_block(obj):
    return f"```json\n{json.dumps(obj, indent=2)}\n```"


class Command(BaseCommand):
    help = (
        'Generate SNMP/data/template_profile_context.md — the LLM context file '
        'for SNMP template and profile generation. Re-run whenever official '
        'profiles or device templates are added or modified.'
    )

    def add_arguments(self, parser):
        parser.add_argument(
            '--output',
            default=None,
            help=(
                'Path to write the context file. '
                'Defaults to SNMP/data/template_profile_context.md'
            ),
        )

    def handle(self, *args, **options):
        base = os.path.join(settings.BASE_DIR, 'SNMP', 'data')

        profiles_dir   = os.path.join(base, 'official_profiles')
        templates_dir  = os.path.join(base, 'official_device_templates')
        normalizers_fp = os.path.join(base, 'normalizers.json')

        output_path = options['output'] or os.path.join(base, 'template_profile_context.md')

        # ── Load raw data ──────────────────────────────────────────────────────

        raw_profiles  = _load_json_dir(profiles_dir)   # [(name, dict), …]
        raw_templates = _load_json_dir(templates_dir)  # [(name, dict), …]

        if not raw_profiles:
            self.stdout.write(self.style.ERROR(f'No profile JSON files found in {profiles_dir}'))
            return
        if not raw_templates:
            self.stdout.write(self.style.ERROR(f'No template JSON files found in {templates_dir}'))
            return

        # ── Index profiles by their name field (used for template → profile lookup) ──

        profile_by_name = {}
        for _fname, p in raw_profiles:
            profile_by_name[p.get('name', _fname)] = p

        # ── Load normalizers ───────────────────────────────────────────────────

        normalizers = None
        if os.path.isfile(normalizers_fp):
            try:
                with open(normalizers_fp, 'r', encoding='utf-8') as fh:
                    normalizers = json.load(fh)
            except Exception:
                pass

        # ── Build context document ─────────────────────────────────────────────

        lines = []

        lines += [
            '# SNMP Template & Profile Context',
            '',
            'This file is the authoritative reference for the LLM that generates new SNMP',
            'device templates and profiles for LogstashUI. It is generated automatically from',
            'the bundled JSON files in `SNMP/data/` and committed to the repository.',
            '',
            '**Do not edit this file by hand.** Re-generate it with:',
            '```',
            'uv run python manage.py generate_template_profile_context',
            '```',
            '',
            '---',
            '',
        ]

        # ── Section 1: Device Templates ────────────────────────────────────────

        lines += [
            '## Section 1 — Device Templates',
            '',
            'Each device template groups one or more profiles together under a single',
            'vendor/product identity. The `profiles` list contains the names of the profiles',
            'that are included in this template. `matching_rules` are case-insensitive',
            'substrings matched against a device\'s `sysDescr` for auto-assignment.',
            '',
            '> When generating a **new device template**, choose a unique `name` in',
            '> `snake_case`, set appropriate `vendor`/`product`/`model` fields, list the',
            '> profile names the template should include, and provide at least one',
            '> `matching_rules` entry if the target device exposes a recognisable `sysDescr`.',
            '',
        ]

        for _fname, tmpl in raw_templates:
            clean = _strip_internal(tmpl)
            tmpl_name = clean.get('name', _fname)

            # Embed the full profile JSON for every profile the template references
            profile_refs = clean.pop('profiles', []) if isinstance(clean.get('profiles'), list) else []

            lines += [
                f'### {tmpl_name}',
                '',
                _json_block(clean),
                '',
            ]

            if profile_refs:
                lines += [
                    f'**Profiles included in `{tmpl_name}`:**',
                    '',
                ]
                for pname in profile_refs:
                    profile_data = profile_by_name.get(pname) or profile_by_name.get(f'{pname}.json')
                    if profile_data:
                        lines += [
                            f'#### `{pname}`',
                            '',
                            _json_block(_strip_internal(profile_data)),
                            '',
                        ]
                    else:
                        lines += [
                            f'#### `{pname}`',
                            '',
                            '_Profile definition not found in bundled files._',
                            '',
                        ]

        lines += ['---', '']

        # ── Section 2: All Profiles ────────────────────────────────────────────

        lines += [
            '## Section 2 — Full Profile Catalog',
            '',
            'Complete listing of every official profile. Profiles define which SNMP OIDs',
            'to collect and how to post-process the values (normalizers).',
            '',
            '**Profile JSON schema:**',
            '- `name` — unique snake_case identifier (e.g. `cisco_system_metrics`)',
            '- `description` — one sentence describing what is collected',
            '- `vendor` / `product` / `model` — target device scope (`"Any"` for generic profiles)',
            '- `get` — map of `"ecs.field.path": "OID"` for scalar GETs',
            '- `walk` — map of `"ecs.field.path": "OID"` for SNMP walks',
            '- `table` — map of table names → `columns` map of `"column_name": "OID"`',
            '- `normalizers` — optional list of post-processing operations (see Section 3)',
            '',
            '> When generating a **new profile**, choose a `name` prefixed with the vendor',
            '> (or `generic_` for broadly applicable profiles), use ECS-aligned dot-notation',
            '> field names, and add `normalizers` where raw SNMP values need conversion.',
            '',
        ]

        for _fname, profile in raw_profiles:
            clean = _strip_internal(profile)
            pname = clean.get('name', _fname)
            lines += [
                f'### `{pname}`',
                '',
                _json_block(clean),
                '',
            ]

        lines += ['---', '']

        # ── Section 3: Normalizer Reference ───────────────────────────────────

        lines += [
            '## Section 3 — Normalizer Reference',
            '',
            'Normalizers are post-processing steps declared in the `normalizers` array of a',
            'profile. They run after OID collection to transform raw SNMP values into usable',
            'metrics.',
            '',
            '**Scope rules:**',
            '- `"scope": "get"` — runs on scalar GET results before table processing',
            '- `"scope": "table"` — runs on per-row table results; `field` paths must include',
            '  the table name prefix (e.g. `interface.admin_status`, not just `admin_status`)',
            '',
        ]

        if normalizers:
            for op_name, op_def in normalizers.items():
                lines += [
                    f'### `{op_name}` — {op_def.get("label", "")}',
                    '',
                    op_def.get('description', ''),
                    '',
                    _json_block(op_def),
                    '',
                ]
        else:
            lines.append('_normalizers.json not found._\n')

        lines += ['---', '']

        # ── Write output ───────────────────────────────────────────────────────

        content = '\n'.join(lines)

        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as fh:
            fh.write(content)

        profile_count  = len(raw_profiles)
        template_count = len(raw_templates)
        size_kb = round(os.path.getsize(output_path) / 1024, 1)

        self.stdout.write(self.style.SUCCESS(
            f'Written {output_path}  '
            f'({template_count} templates, {profile_count} profiles, {size_kb} KB)'
        ))
        self.stdout.write(
            'Commit this file alongside any changes to official_profiles/ or '
            'official_device_templates/.'
        )
